"""Generate the static JSON Schema files from the Kosli API (source of truth).

The two schemas published as static assets from this repo are generated by the
`kosli-dev/server` API from its Pydantic models. Editing the committed copies by
hand lets them drift from what the API actually enforces, so this script fetches
them from the live public endpoints and writes them to the published paths.

| Published file                | API endpoint                                    |
|-------------------------------|-------------------------------------------------|
| schemas/flow-template/v1.json | GET /api/v2/schemas/flow-template/v1            |
| schemas/policy/v1.json        | GET /api/v2/schemas/environment-policy/v1       |

Usage:
    python scripts/update_schemas.py            # regenerate the files in place
    python scripts/update_schemas.py --check     # exit non-zero if they drift
"""
import argparse
import json
import sys
from pathlib import Path

import requests

_API_BASE = "https://app.kosli.com/api/v2/schemas"
_REPO_ROOT = Path(__file__).resolve().parent.parent

# endpoint path (under _API_BASE) -> committed file (relative to repo root)
_SCHEMAS = {
    "flow-template/v1": "schemas/flow-template/v1.json",
    "environment-policy/v1": "schemas/policy/v1.json",
}


def fetch_schema(endpoint):
    """Fetch the schema served at endpoint and return it as a dict."""
    url = f"{_API_BASE}/{endpoint}"
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    return response.json()


def render(schema):
    """Return schema as a deterministic, pretty-printed JSON string with a trailing newline."""
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if any committed file differs from the API.",
    )
    args = parser.parse_args()

    drifted = []
    for endpoint, rel_path in _SCHEMAS.items():
        target = _REPO_ROOT / rel_path
        generated = render(fetch_schema(endpoint))

        if args.check:
            current = target.read_text(encoding="utf-8") if target.exists() else None
            if current != generated:
                drifted.append(rel_path)
                print(f"drift: {rel_path} differs from {_API_BASE}/{endpoint}")
            else:
                print(f"ok:    {rel_path}")
            continue

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(generated, encoding="utf-8")
        print(f"wrote: {rel_path} (from {_API_BASE}/{endpoint})")

    if args.check and drifted:
        print(
            f"\n{len(drifted)} schema file(s) are out of date. "
            "Run `python scripts/update_schemas.py` to regenerate.",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
